### ISSUE TITLE
Touch support 

### ISSUE THREAD

**Issue by kamiz22** [jonahallibone/react-tilty#1]
Hi, first thanks for creating this nice library for react!
Mouse hover works great, would it be possible to add support for touch gestures, since most of my web apps is not used on computers?

**Comment by jonahallibone** [comment]
Hi @kamiz22, unfortunately because this library is only a port, we try to keep the options restrained to what is available in the vanilla js library. If you notice better performance there, let us know and we will get right on adding it to our version. Thanks!

**Comment by csandman** [comment]
@kamiz22  While there is no touch support, you should check out the gyroscope option!  It works off of phone tilt angle.  This is probably the best mobile support we will be able to offer.

Here's an example (try this link on a phone)

https://9yknlm9xrp.codesandbox.io/
