### ISSUE TITLE
Glare effect

### ISSUE THREAD

**Issue by kamiz22** [jonahallibone/react-tilty#2]
Not sure why glare effect doesn't work but I set options as follows:
```
        glare: true,
        'max-glare': 0.5,
        'glare-prerender': false,
```
Any idea what could be wrong?

**Comment by jonahallibone** [comment]
@kamiz22 We will take a look at this, but if you want to submit a PR feel free to

**Comment by csandman** [comment]
@kamiz22 I tried it out and it works fine for me!  I made a demo here to show you how the setup should look exactly:

https://codesandbox.io/s/2vm8k8x6n?fontsize=14

You don't need the `glare-prerender` property unless you're setting it to true, it defaults to false.  I also left two commented out lines in there which are the alternative way of setting this property.  Let me know if this solves your problem!

**Comment by kamiz22** [comment]
Tnx it works.
